backend:
  name: git-gateway
  branch: main

media_folder: "public/images/articles"
public_folder: "/images/articles"

collections:
  - name: "techniques"
    label: "Techniques"
    label_singular: "Article technique"
    folder: "src/content/techniques"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Contenu", name: "body", widget: "markdown" }

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

locale: "fr"
